FROM ubuntu:20.04
LABEL github="https://github.com/CollaborativeFederatedLearningTutorials/base_docker"
LABEL docs="https://fl-tutorials.org"
LABEL version=1.0

# Install fresh Python and dependencies for build-from-source
RUN apt-get update && apt-get install -y --no-install-recommends software-properties-common
RUN add-apt-repository ppa:deadsnakes/ppa
RUN apt-get update &&  apt-get install -y  python3.9 python3-pip libjpeg8-dev zlib1g-dev python3-dev libpython3.9-dev libffi-dev libgl1 git
RUN python3.9 -m pip install --no-cache-dir --upgrade pip
# EXPLICITLY install cpu versions of torch/torchvision (not all versions have +cpu modes on PyPI...)
RUN python3.9 -m pip install --no-cache-dir torch==2.1.2+cpu torchvision==0.16.2+cpu torchaudio==2.1.2 --index-url https://download.pytorch.org/whl/cpu
RUN python3.9 -m pip install --no-cache-dir openvino-dev==2023.0.1 opencv-python-headless mlcube_docker
RUN git clone https://github.com/mlcommons/GaNDLF
RUN python3.9 -m pip --no-cache-dir install -e ./GaNDLF

# Install MedPerf
RUN git clone -b fl-poc https://github.com/hasan7n/medperf
RUN python3.9 -m pip --no-cache-dir install -e medperf/cli/
RUN python3.9 -m pip --no-cache-dir install -r medperf/server/requirements.txt
RUN python3.9 -m pip --no-cache-dir install -r medperf/server/test-requirements.txt

### further installation goes here