FROM ubuntu:20.04
LABEL github="https://github.com/CollaborativeFederatedLearningTutorials/base_docker"
LABEL docs="https://fl-tutorials.org"
LABEL version=1.0

# Install fresh Python and dependencies for build-from-source
RUN apt-get update && apt-get install -y software-properties-common
RUN add-apt-repository ppa:deadsnakes/ppa
RUN apt-get update &&  apt-get install -y  python3.9 python3-pip libjpeg8-dev zlib1g-dev python3-dev libpython3.9-dev libffi-dev libgl1
RUN python3.9 -m pip install --upgrade pip
# EXPLICITLY install cpu versions of torch/torchvision (not all versions have +cpu modes on PyPI...)
RUN python3.9 -m pip install torch==2.1.0+cpu torchvision==0.16.0+cpu torchaudio==2.1.0 --index-url https://download.pytorch.org/whl/cpu
RUN python3.9 -m pip install openvino-dev==2023.0.1 opencv-python-headless mlcube_docker
RUN python3.9 -m pip install gandlf

# Install git
RUN apt-get install -y git
# Install MedPerf
RUN git clone -b fl-poc https://github.com/hasan7n/medperf
RUN cd medperf && python3.9 -m pip install -e cli/
RUN cd medperf && python3.9 -m pip install -r server/requirements.txt
RUN cd medperf && python3.9 -m pip install -r server/test-requirements.txt

### further installation goes here